version: "3.5"
services:
  ig:
    image: greboid/ig
    volumes:
      - config:/app/config/
      - thumbs:/app/thumbs/
    links:
      - database
    restart: always
    ports:
      - 8080:80
  database:
    image: mysql:8
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=ig
      - MYSQL_USER=ig
      - MYSQL_PASSWORD=ig
    restart: always

volumes:
  config:
  database:
  thumbs:
